### ISSUE TITLE
Smart builder v0.3.0 incompatible with maven 3.2.5

### ISSUE THREAD

**Issue by riccardo-gorza** [takari/takari-smart-builder#2]
Using takari plugins
* takari-smart-builder-0.3.0.jar
* takari-filemanager-0.8.2.jar
* takari-local-repository-0.10.4.jar

with Maven 3.2.5 generates the following exception (maven 3.2.2 works fine):

```java
constituent[42]: file:/appl/apache-maven-3.2.5/lib/slf4j-api-1.7.5.jar
constituent[43]: file:/appl/apache-maven-3.2.5/conf/logging/
Exception in thread "main" java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class io.takari.maven.builder.smart.BuildMetrics$ThreadSafeStopwatch
	at io.takari.maven.builder.smart.BuildMetrics$ThreadSafeStopwatch.<init>(BuildMetrics.java:35)
	at io.takari.maven.builder.smart.BuildMetrics$ThreadSafeStopwatch.<init>(BuildMetrics.java:33)
	at io.takari.maven.builder.smart.BuildMetrics.<init>(BuildMetrics.java:59)
	at io.takari.maven.builder.smart.ProjectsBuildMetrics.<init>(ProjectsBuildMetrics.java:18)
	at io.takari.maven.builder.smart.SmartBuilderImpl.<init>(SmartBuilderImpl.java:127)
	at io.takari.maven.builder.smart.SmartBuilder.build(SmartBuilder.java:31)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by ifedorenko** [comment]
Version 0.4.0, the latest released, is compatible with maven 3.2.5

**Comment by riccardo-gorza** [comment]
Yep, sorry and thanks for the hint. Used the examples from the book: http://takari.io/book/30-team-maven.html#installation-and-usage . Updating the book examples or provide an information where to look up the latest plugins would help.

**Comment by riccardo-gorza** [comment]
Another minor issue: In http://mvnrepository.com/artifact/io.takari.maven/takari-smart-builder/0.4.0 . Try to download the jar through the "download jar-link". This gives you a 404 because of the ".takari" extension.

**Comment by ifedorenko** [comment]
Thanks. We'll update the book to mention smartbuilder 0.4.

I suggest you report the problem with download link to whoever maintains http://mvnrepository.com, we certainly have no control or influence how they implement their service.
